### ISSUE TITLE
CLI CI not working for env-cmd package not found

### ISSUE THREAD

**Issue by antoniogiordano** [getapper/restlessness#108]

**Comment by androsanta** [comment]
Does this happen for every cli command?

**Comment by antoniogiordano** [comment]
I think only for the CLI because it used env-cmd to build frontend

**Comment by androsanta** [comment]
Possible [memory leak](https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas) from react-scripts
