### ISSUE TITLE
Migrate configs file management from CLI package

### ISSUE THREAD

**Issue by antoniogiordano** [getapper/restlessness#18]
All the configs file management is handled in the CLI project, under the run command. All the code is basically contained into the cli backend project. This is not optimal right now, since also other plugins, daos, auths, etc, should have the chance to add a model, for instance. The idea is to move all the backend models and path services logics, into this generale package, and CLI run command will just be a web interface wrapper between the developer and these basics commands.

**Comment by androsanta** [comment]
So the cli backend will use configs file management from the `@restlessness/utilities` package, Am I right? I'm looking at the branch `feature/utilities-configs-handling`

**Comment by antoniogiordano** [comment]
Correct! Please align your local branch to this one, so we have the same code base.
I'm also moving the init project command to utilities.
The final goal is to have all the logic there, with pure callable functions, useful for testing as well, and CLI and Web interfaces will just wrap user commands with these logics.
