### ISSUE TITLE
restlessness dev: Handle serve not installed

### ISSUE THREAD

**Issue by antoniogiordano** [getapper/restlessness#30]
If serve is not installed globally I receive this:

RESTLESSNESS error:
/bin/sh: serve: command not found

I think we can catch this or we can even test if it is available or not before launching all the commands

**Comment by antoniogiordano** [comment]
Also, the process doesn't exit on this error @androsanta

**Comment by androsanta** [comment]
we could use shelljs and use the `which` command to check if all peerDependencies are satisfied, or check the platform and use `where` on windows and `which` on linux/mac to avoid another dependency
