### ISSUE TITLE
When adding mongo dao, we should include permission to invoke lambdas automatically in provider section

### ISSUE THREAD

**Issue by antoniogiordano** [getapper/restlessness#92]
i.e. 

  "provider": {
    "name": "aws",
    "runtime": "nodejs12.x",
    "region": "us-west-2",
    "timeout": 25,
    "iamRoleStatements": [
      {
        "Effect": "Allow",
        "Action": [
          "lambda:InvokeFunction"
        ],
        "Resource": "*"
      }
    ]
  },

**Comment by androsanta** [comment]
Currently the serverless-mongo-proxy package is a peerDependency of @restlessness/dao-mongo, so a user must install it explicitly. Should we install it automatically when adding dao-mongo?
